# Simple RNN

Recurrent Neural Network

## Preparation

### Load the Library

In [1]:
import tensorflow as tf
import numpy as np
from datetime import datetime

tf.__version__

'2.7.4'

### Prepare Training Data

In [6]:
# Movie Reviews Dataset
train_ds, test_ds = tf.keras.datasets.imdb.load_data(num_words=10000)   # Top 10k frequency

# Statistics Info.
_train_x_lens = [len(x) for x in train_ds[0]]
np.max(_train_x_lens), np.min(_train_x_lens), np.mean(_train_x_lens), np.median(_train_x_lens)

(2494, 11, 238.71364, 178.0)

In [7]:
# Padding: In Rnn, the data on the back is more important, so the front is padding with "0"
train_x = tf.keras.preprocessing.sequence.pad_sequences(train_ds[0], 800)  # padding="pre" - default
test_x = tf.keras.preprocessing.sequence.pad_sequences(test_ds[0], 800)
train_y, test_y = train_ds[1], test_ds[1]

## Define RNN Model

In [9]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(input_dim=10000, output_dim=32),
    tf.keras.layers.SimpleRNN(units=32, activation="tanh"),
    tf.keras.layers.Dense(units=1, activation="sigmoid")
])
model.compile(optimizer="rmsprop", loss="binary_crossentropy", metrics=["accuracy"])

## Training Model

In [11]:
%%time
model.fit(train_x, train_y, batch_size=128, epochs=5, validation_data=(test_x, test_y))

Epoch 1/5
196/196 [==============================] - 74s 380ms/step - loss: 0.6521 - accuracy: 0.6025 - val_loss: 0.7633 - val_accuracy: 0.5682
Epoch 2/5
196/196 [==============================] - 75s 383ms/step - loss: 0.4098 - accuracy: 0.8231 - val_loss: 0.4784 - val_accuracy: 0.7760
Epoch 3/5
196/196 [==============================] - 74s 378ms/step - loss: 0.2883 - accuracy: 0.8838 - val_loss: 0.4568 - val_accuracy: 0.7838
Epoch 4/5
196/196 [==============================] - 74s 379ms/step - loss: 0.2145 - accuracy: 0.9181 - val_loss: 0.5377 - val_accuracy: 0.7649
Epoch 5/5
196/196 [==============================] - 75s 384ms/step - loss: 0.1505 - accuracy: 0.9447 - val_loss: 0.5455 - val_accuracy: 0.7783
CPU times: user 11min 59s, sys: 45.6 s, total: 12min 45s
Wall time: 6min 12s


: 

## Result

* Home PC
```log
Epoch 5/5
196/196 [==============================] - 75s 384ms/step - loss: 0.1505 - accuracy: 0.9447 - val_loss: 0.5455 - val_accuracy: 0.7783
CPU times: user 11min 59s, sys: 45.6 s, total: 12min 45s
Wall time: 6min 12s
```